[package]
name = "binal"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.9"
hex = "0.4.3"
notify = "6.1.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
