[package]
name = "binal"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.9"
serde = { version = "1.0.204", features = ["derive"]}
tokio = { version = "1.38.0", features = ["full"] }
serde_json = "1.0.122"

binal-project = { path = "../binal-project" }
