[package]
name = "binal-project"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcode = { version = "0.6.3", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"]}
tokio = { version = "1.38.0", features = ["full"] }
