[package]
name = "binal-database-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
rusqlite = { version = "0.32.0", features = [ "bundled"] }
syn = "2.0.71"
